### ISSUE TITLE
Can you please provide screenshot or demo?

### ISSUE THREAD

**Issue by alvanrahimli** [onionyst/reader#1]
I'm interested at self-hosting and trying out this software, it would be very nice if you could show some screenshots or provide a demo webpage to try out.

Thanks in advance :)

**Comment by onionyst** [comment]
In fact, this project is primarily designed for personal usage for the FreshRSS module of [Reeder](https://reederapp.com), as I wanted to have some custom pre-processing for the RSS. So I mainly implemented the FreshRSS core APIs and a [RSSHub](https://github.com/DIYgod/RSSHub)-like aggregator module, and currently without any backend managing UI. It looks like this from macOS Reeder: 

<img width="600" alt="screenshot" src="https://user-images.githubusercontent.com/14269397/207493889-c1e52584-7685-4f24-b178-4e7513a32031.png">

If you want to try it out, you can run `docker compose -f deployments/compose.yaml up -d` to start a Docker container and connect from Reeder client. I have also added an `account` command to provide naive user addings. 

I'm glad to see someone interest in this project. Unfortunately, I don't have much time to work on this at the moment. Future plans include adding new RSS feeds under the framework and modules such as RSS feed managing (cmd or webpage).

**Comment by alvanrahimli** [comment]
Thanks a lot for your response. 

I looked at the project and saw this is not exactly what I wanted, that is why had to go with miniflux. 

Good luck 🍀
